#! /bin/sh
#  ____ _____ 
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |  	http://www.youtube.com/c/DistroTube
# | |_| || |  	http://www.gitlab.com/dwt1/ 
# |____/ |_|  	
#        
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### AUTOSTART ####
sxhkd &
picom &
nitrogen --restore &
polybar example &
nm-applet &
blueberry-tray &
exec lxpolkit &
exec setxkbmap pl &
exec dbus-update-activation-environment --all &
#cbatticon
#exec xrandr -s 1600x900
#### MONITORS ####
bspc monitor -d 1 2 3 4 5 6 7 8 9 
### BSPWM configuration ####
bspc config border_radius                 5
bspc config border_width                  3
bspc config window_gap                    3
bspc config top_padding                   21
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#aa6790e0"
bspc config active_border_color	          "#6790eb"
bspc config focused_border_color	      "#6790eb"
bspc config presel_feedback_color	      "#aa6790e0"
bspc config urgent_border_color 	      "#aa6790e0"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_LVDS1-0)

